//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaberSitesi.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Haber
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Ozet { get; set; }
        public string Icerik { get; set; }
        public byte[] Resim { get; set; }
        public string ResimTipi { get; set; }
        public int Durum { get; set; }
        public bool Goster { get; set; }
        public int Kullanici_Id { get; set; }
        public int Kategori_Id { get; set; }
    
        public virtual tbl_Kategori tbl_Kategori { get; set; }
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
    }
}
